# Generated by Django 3.1.4 on 2020-12-23 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating1', models.IntegerField(default=0, verbose_name='Rating1')),
                ('rating2', models.IntegerField(default=0, verbose_name='Rating2')),
                ('rating3', models.IntegerField(default=0, verbose_name='Rating3')),
                ('rating4', models.IntegerField(default=0, verbose_name='Rating4')),
                ('rating5', models.IntegerField(default=0, verbose_name='Rating5')),
            ],
        ),
        migrations.AddField(
            model_name='ideas',
            name='rating',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Content.rating'),
        ),
    ]
