# Generated by Django 3.1.4 on 2020-12-23 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0002_auto_20201223_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideas',
            name='rating',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ideas', to='Content.rating'),
        ),
    ]
