# Generated by Django 3.1.4 on 2021-03-02 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0004_auto_20201224_0419'),
    ]

    operations = [
        migrations.CreateModel(
            name='ICategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя категорий')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='IcatP/', verbose_name='Фото категорий')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категорий',
            },
        ),
        migrations.AlterModelOptions(
            name='ideas',
            options={'verbose_name': 'Идея', 'verbose_name_plural': 'Идей'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': 'Фото для Идей', 'verbose_name_plural': 'Фото для Идей'},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name': 'Рейтинг', 'verbose_name_plural': 'Рейтинги'},
        ),
        migrations.RemoveField(
            model_name='ideas',
            name='rating',
        ),
        migrations.AddField(
            model_name='ideas',
            name='rating',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='ideas', to='Content.Rating'),
        ),
        migrations.AddField(
            model_name='ideas',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Content.icategory'),
        ),
    ]
