# Generated by Django 3.1.4 on 2021-03-02 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0005_auto_20210302_0505'),
    ]

    operations = [
        migrations.AddField(
            model_name='icategory',
            name='ficon',
            field=models.CharField(default=1, max_length=255, verbose_name='Для иконки'),
            preserve_default=False,
        ),
    ]
