# Generated by Django 3.1.4 on 2021-03-02 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0012_auto_20210302_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='idea',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='Content.ideas'),
        ),
    ]
